<?php
 $title			Your site title
 $author		Your name or your company name
 $copyright		Add some copyright notice here
 $keywords		Add all your keywords in here (separate each keyword by a comma and space)
 $description	This is the description search engines show when listing your site.
 $langcode		en
 $rating		general
 $index			index
 $follow		follow
 $pragma		1
 $icon			favicon.ico
 $header		<meta name=\"revisit-after\" content=\"7 days\">
?>